services:
  main:
    in:
      type: stream
      stream:
        type: number
    out:
      type: number
operators:
  Multiply:
    operator: slang.math.arith.Multiply
  Reduce:
    operator: slang.control.Reduce
    properties:
      emptyValue: 1
    generics:
      itemType:
        type: number
connections:
  (:
  - (Reduce
  Multiply):
  - (Reduce.reducer
  Reduce):
  - )
  Reduce.reducer):
  - (Multiply
